backend:
  name: 'github'
  repo: 'elpachongco/elpachongco.github.io'
  branch: 'master'
#     # api_root: 'https://api.github.com'
#     # site_domain: 'elpachongco.github.io'
#     # base_url: 'https://api.netlify.com'
#     # auth_endpoint: 'auth'

media_folder: 'assets/img/uploads'
public_folder: 'img/uploads'

collections:
  - name: 'post' # Used in routes, e.g., /admin/collections/blog
    label: 'Blog' # Used in the UI
    folder: 'content/post' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime', format: 'YYYY-MM-DDTHH:mm:ss.SSSZ'}
        # - { label: 'Featured Image', name: 'thumbnail', widget: 'image' }
        # - { label: 'Rating (scale of 1-5)', name: 'rating', widget: 'number' }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'shorts' # Used in routes, e.g., /admin/collections/blog
    label: 'Shorts' # Used in the UI
    folder: 'content/shorts' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime', format: 'YYYY-MM-DDTHH:mm:ss.SSSZ'}
        # - { label: 'Featured Image', name: 'thumbnail', widget: 'image' }
        # - { label: 'Rating (scale of 1-5)', name: 'rating', widget: 'number' }
      - { label: 'Body', name: 'body', widget: 'markdown' }


